### ISSUE TITLE
Cant find variableTextEncoder

### ISSUE THREAD

**Issue by nlaitanatix** [Gozala/web-encoding#9]
In lib.browser.js, react native throws me that error. 

I have installed v1.0.4

**Comment by Gozala** [comment]
@nlaitanatix I have no real experience with react native, but given what you said it seems to me that react native is recognizing `browser` field  in package.json and loads `lib.browser.js` but then fails because unlike browsers it does not have [`TextEncoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) API 😞

I am afraid at the moment I do not have time to start digging into react native to fix this, but I'd be happy to take a PR if you're willing to take on the challenge.

**Comment by jasheal** [comment]
@Gozala We have also come across this issue as our dependency tree is `@veramo/core` -> `did-jwt` -> `uint8arrays` -> `web-encoding`.  See issue: https://github.com/uport-project/veramo-website/issues/33

This breaks in React Native. The temporary solution I have is to import a `text-encoding` polyfill. What do you think of having this polyfill live directly in this lib and be imported if no window object is found in the browser?

**Comment by Gozala** [comment]
> This breaks in React Native. The temporary solution I have is to import a `text-encoding` polyfill. What do you think of having this polyfill live directly in this lib and be imported if no window object is found in the browser?

Generally that sounds good. However I am not sure if it is possible to do without increasing bundle sizes for browsers, which I would not like. @jasonhealy is there some export condition that would satisfy react native case ? If so I would be more than happy to take a pull that adds a condition into export maps to include the shim.

https://github.com/Gozala/web-encoding/blob/075f2fed99c40882f3e60500005bafbc22264208/package.json#L14-L20 

If that is not possible, then I am not sure what would be a good approach. I would have suggested creating another library union of this and polyfill, but sounds lie it would not solve the problem as `uint8arrays` will need to update too.

@achingbrain what do you think about

**Comment by somay** [comment]
@Gozala I totally agree with you that increase of browser bundle size should be avoided.
Would you mind if I propose a PR to resolve this React Native specific issue?
I'm also encountering this when developing a mobile app.

In my experiment the React Native Packager seems to pick the `react-native` field in `package.json` rather than the `browser` field (not these in the `exports` field).
So I'm going to add that field in `package.json` and include the `text-encoding` polyfill as `optionalDependencies`.

**Comment by Gozala** [comment]
Sure that sounds reasonable, thanks
